M48
; DRILL file {KiCad (6.0.4)} date Mon Feb  6 16:45:06 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-06T16:45:06+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X9.8483Y-1.8541
X9.8483Y-5.3974
X13.3916Y-1.8541
X13.3916Y-5.3974
T0
M30
