M48
; DRILL file {KiCad (6.0.4)} date Mon Feb  6 17:29:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-06T17:29:47+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X10.803Y-1.3766
X10.803Y-4.9199
X14.3463Y-1.3766
X14.3463Y-4.9199
T0
M30
